apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gogs-role-bind
subjects:
  - kind: ServiceAccount
    name: gogs-sa
roleRef:
  kind: Role
  name: gogs-role
  apiGroup: rbac.authorization.k8s.io